<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="epbyminw4546.minsk.epam.com" name="com.testngtutorial.MyTestNGTutorial.tests.ListenerTest" tests="3" failures="1" timestamp="7 Jul 2016 11:32:02 GMT" time="0.008" errors="1">
  <testcase name="Test1Succcess" time="0.007" classname="com.testngtutorial.MyTestNGTutorial.tests.ListenerTest"/>
  <testcase name="Test2Skip" time="0.000" classname="com.testngtutorial.MyTestNGTutorial.tests.ListenerTest"/>
  <testcase name="Test2Fail" time="0.001" classname="com.testngtutorial.MyTestNGTutorial.tests.ListenerTest">
    <error type="java.lang.AssertionError" message="I&#039;m asserting false expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: I'm asserting false expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.testngtutorial.MyTestNGTutorial.tests.ListenerTest.Test2Fail(ListenerTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1194)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.testngtutorial.MyTestNGTutorial.runner.Runner.main(Runner.java:63)
]]>
    </error>
  </testcase> <!-- Test2Fail -->
</testsuite> <!-- com.testngtutorial.MyTestNGTutorial.tests.ListenerTest -->
